// AUTO-GENERATED by scripts/generateStocksSeedData.mjs — do not edit by hand
import type { Trade, DailyMood } from './db';

export const SEED_STOCKS_JOURNAL = {
  name: 'US Stocks – Early 2026',
  startingBalance: 25000,
  createdAt: '2026-01-02T00:00:00.000Z',
  updatedAt: '2026-02-27T00:00:00.000Z',
};

type SeedTrade = Omit<Trade, 'id' | 'journalId'>;
type SeedMood  = Omit<DailyMood, 'id' | 'journalId'>;

export function getSeedStocksTrades(): SeedTrade[] {
  return [
  {
    "openDate": "2026-01-05T14:37:00.000Z",
    "closeDate": "2026-01-05T17:10:00.000Z",
    "timeframe": "1m",
    "pair": "AMZN",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": false,
      "Waited for first 5-min candle to close?": false,
      "Stop below gap level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 17,
    "result": "Loss",
    "rr": 0.91,
    "sl": 3.86,
    "tp": 3.51,
    "pnl": -62.62,
    "netPnl": -62.71,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Earnings missed badly. I had too large a position for the uncertainty involved.",
        "fomo": 5,
        "patience": 4,
        "discipline": 4,
        "confidence": 1
      },
      "technical": "Sector rotation out of tech hurt the names I was long despite individual chart being clean.",
      "other": ""
    },
    "duration": 153
  },
  {
    "openDate": "2026-01-05T10:58:00.000Z",
    "closeDate": "2026-01-05T12:50:00.000Z",
    "timeframe": "1m",
    "pair": "GOOGL",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": false,
      "ATR expanding into breakout?": false,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 45,
    "result": "Loss",
    "rr": 0.62,
    "sl": 3.14,
    "tp": 1.95,
    "pnl": -130.02,
    "netPnl": -130.25,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Chased the open gap, no patience for a pullback entry. Paid for it.",
        "fomo": 5,
        "patience": 3,
        "discipline": 3,
        "confidence": 4
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 112
  },
  {
    "openDate": "2026-01-05T09:44:00.000Z",
    "closeDate": "2026-01-05T12:59:00.000Z",
    "timeframe": "1D",
    "pair": "GOOGL",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 7,
    "result": "Win",
    "rr": 3.66,
    "sl": 0.84,
    "tp": 3.07,
    "pnl": 18.37,
    "netPnl": 18.33,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 3,
        "patience": 3,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "AMD made a clean higher low above VWAP, entered on micro breakout, target hit in 45 mins.",
      "other": ""
    },
    "duration": 195
  },
  {
    "openDate": "2026-01-06T13:08:00.000Z",
    "closeDate": "2026-01-06T16:39:00.000Z",
    "timeframe": "15m",
    "pair": "AMZN",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": false,
      "Size risk ≤ 1% of account?": false
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 38,
    "result": "Win",
    "rr": 2.16,
    "sl": 3.25,
    "tp": 7.02,
    "pnl": 231.81,
    "netPnl": 231.62,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Earnings play worked as expected. Sizing was conservative — left money but protected capital.",
        "fomo": 4,
        "patience": 2,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "AMD made a clean higher low above VWAP, entered on micro breakout, target hit in 45 mins.",
      "other": ""
    },
    "duration": 211
  },
  {
    "openDate": "2026-01-06T11:16:00.000Z",
    "closeDate": "2026-01-06T14:28:00.000Z",
    "timeframe": "15m",
    "pair": "NVDA",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 6,
    "result": "Win",
    "rr": 2.04,
    "sl": 1.1,
    "tp": 2.25,
    "pnl": 12.68,
    "netPnl": 12.65,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 2,
        "patience": 3,
        "discipline": 3,
        "confidence": 3
      },
      "technical": "META earnings-day gap up, waited 15 mins, entered the bull-flag breakout at open range high.",
      "other": ""
    },
    "duration": 192
  },
  {
    "openDate": "2026-01-07T15:29:00.000Z",
    "closeDate": "2026-01-07T15:54:00.000Z",
    "timeframe": "1D",
    "pair": "QQQ",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 61,
    "result": "Win",
    "rr": 2.72,
    "sl": 1.32,
    "tp": 3.59,
    "pnl": 210.89,
    "netPnl": 210.59,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 4,
        "patience": 2,
        "discipline": 5,
        "confidence": 4
      },
      "technical": "AAPL formed an inside day then broke higher on iPhone unit beat. Held through pullback.",
      "other": ""
    },
    "duration": 25
  },
  {
    "openDate": "2026-01-08T12:56:00.000Z",
    "closeDate": "2026-01-08T13:53:00.000Z",
    "timeframe": "5m",
    "pair": "AAPL",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": false,
      "Waited for first 5-min candle to close?": false,
      "Stop below gap level?": false
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 33,
    "result": "Break Even",
    "rr": 0.62,
    "sl": 3.09,
    "tp": 1.92,
    "pnl": 9.69,
    "netPnl": 9.52,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved to break-even when I saw the 5-min bar stall. Missed the rest of the move.",
        "fomo": 3,
        "patience": 3,
        "discipline": 1,
        "confidence": 3
      },
      "technical": "QQQ breakout above 3-month ascending triangle. Entered on retest, hit measured target.",
      "other": ""
    },
    "duration": 57
  },
  {
    "openDate": "2026-01-08T14:59:00.000Z",
    "closeDate": "2026-01-08T17:22:00.000Z",
    "timeframe": "1D",
    "pair": "NVDA",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": false,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": false,
      "Volume confirming?": false
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 62,
    "result": "Loss",
    "rr": 1.08,
    "sl": 2.83,
    "tp": 3.06,
    "pnl": -156.04,
    "netPnl": -156.35,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Chased the open gap, no patience for a pullback entry. Paid for it.",
        "fomo": 5,
        "patience": 2,
        "discipline": 2,
        "confidence": 2
      },
      "technical": "Opened at key support, bounced briefly, then broke down. Was too early on the long.",
      "other": ""
    },
    "duration": 143
  },
  {
    "openDate": "2026-01-09T14:40:00.000Z",
    "closeDate": "2026-01-09T18:07:00.000Z",
    "timeframe": "15m",
    "pair": "AAPL",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": false,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 66,
    "result": "Win",
    "rr": 3.71,
    "sl": 0.37,
    "tp": 1.39,
    "pnl": 85.04,
    "netPnl": 84.71,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 4,
        "patience": 2,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 207
  },
  {
    "openDate": "2026-01-09T12:34:00.000Z",
    "closeDate": "2026-01-09T14:35:00.000Z",
    "timeframe": "15m",
    "pair": "NVDA",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": false,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 58,
    "result": "Win",
    "rr": 1.47,
    "sl": 3.59,
    "tp": 5.28,
    "pnl": 275.92,
    "netPnl": 275.63,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 4,
        "patience": 4,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 121
  },
  {
    "openDate": "2026-01-09T15:52:00.000Z",
    "closeDate": "2026-01-09T17:31:00.000Z",
    "timeframe": "15m",
    "pair": "GOOGL",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": false,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": false
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 75,
    "result": "Loss",
    "rr": 0.5,
    "sl": 1.02,
    "tp": 0.51,
    "pnl": -75.05,
    "netPnl": -75.43,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved stop up too early, got shaken out before the real move. Need to trust the structure.",
        "fomo": 4,
        "patience": 2,
        "discipline": 3,
        "confidence": 1
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 99
  },
  {
    "openDate": "2026-01-12T12:04:00.000Z",
    "closeDate": "2026-01-12T13:00:00.000Z",
    "timeframe": "1m",
    "pair": "AMD",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": false,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 40,
    "result": "Win",
    "rr": 1.54,
    "sl": 5.18,
    "tp": 7.98,
    "pnl": 296.86,
    "netPnl": 296.66,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 4,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 56
  },
  {
    "openDate": "2026-01-14T10:35:00.000Z",
    "closeDate": "2026-01-14T12:08:00.000Z",
    "timeframe": "1D",
    "pair": "NVDA",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 34,
    "result": "Win",
    "rr": 2.46,
    "sl": 3.34,
    "tp": 8.23,
    "pnl": 247.36,
    "netPnl": 247.19,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 1,
        "patience": 4,
        "discipline": 2,
        "confidence": 2
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 93
  },
  {
    "openDate": "2026-01-16T13:29:00.000Z",
    "closeDate": "2026-01-16T16:54:00.000Z",
    "timeframe": "5m",
    "pair": "QQQ",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 80,
    "result": "Win",
    "rr": 2.35,
    "sl": 0.47,
    "tp": 1.11,
    "pnl": 80.81,
    "netPnl": 80.41,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 1,
        "patience": 5,
        "discipline": 3,
        "confidence": 3
      },
      "technical": "QQQ breakout above 3-month ascending triangle. Entered on retest, hit measured target.",
      "other": ""
    },
    "duration": 205
  },
  {
    "openDate": "2026-01-19T13:24:00.000Z",
    "closeDate": "2026-01-19T16:53:00.000Z",
    "timeframe": "5m",
    "pair": "AMZN",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": false,
      "Stop below gap level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 8,
    "result": "Loss",
    "rr": 1.27,
    "sl": 3.33,
    "tp": 4.23,
    "pnl": -25.35,
    "netPnl": -25.39,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Bought the top of a news spike. Classic FOMO — always wait for confirmation.",
        "fomo": 5,
        "patience": 4,
        "discipline": 2,
        "confidence": 3
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 209
  },
  {
    "openDate": "2026-01-20T11:58:00.000Z",
    "closeDate": "2026-01-20T12:55:00.000Z",
    "timeframe": "15m",
    "pair": "SPY",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": false,
      "Market internals bullish?": false,
      "Entry on first retest of VWAP from above?": false,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 75,
    "result": "Break Even",
    "rr": 0.76,
    "sl": 2.62,
    "tp": 1.99,
    "pnl": -2.79,
    "netPnl": -3.17,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Too much noise around the Fed statement. Better safe than sorry.",
        "fomo": 5,
        "patience": 4,
        "discipline": 3,
        "confidence": 4
      },
      "technical": "TSLA fakeout above the high — weak close below, sellers in control from open.",
      "other": ""
    },
    "duration": 57
  },
  {
    "openDate": "2026-01-21T13:13:00.000Z",
    "closeDate": "2026-01-21T14:59:00.000Z",
    "timeframe": "15m",
    "pair": "AMZN",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": false,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": false
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 78,
    "result": "Win",
    "rr": 3.4,
    "sl": 3.21,
    "tp": 10.92,
    "pnl": 827.06,
    "netPnl": 826.67,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 5,
        "patience": 3,
        "discipline": 3,
        "confidence": 4
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 106
  },
  {
    "openDate": "2026-01-21T13:13:00.000Z",
    "closeDate": "2026-01-21T15:35:00.000Z",
    "timeframe": "1H",
    "pair": "AMD",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": false,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 44,
    "result": "Loss",
    "rr": 0.55,
    "sl": 3.31,
    "tp": 1.82,
    "pnl": -136.4,
    "netPnl": -136.62,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved stop up too early, got shaken out before the real move. Need to trust the structure.",
        "fomo": 3,
        "patience": 2,
        "discipline": 2,
        "confidence": 3
      },
      "technical": "Setup looked clean on the 5m but daily showed clear resistance just above entry.",
      "other": ""
    },
    "duration": 142
  },
  {
    "openDate": "2026-01-21T11:58:00.000Z",
    "closeDate": "2026-01-21T14:27:00.000Z",
    "timeframe": "5m",
    "pair": "TSLA",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": false,
      "Volume expanding on breakout?": false,
      "RSI < 70 on entry?": false,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 3,
    "lots": 14,
    "result": "Loss",
    "rr": 0.58,
    "sl": 3.27,
    "tp": 1.89,
    "pnl": -42.98,
    "netPnl": -43.05,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Overtraded — took 4 trades, all small losses that added up. Should have stopped after 2.",
        "fomo": 5,
        "patience": 1,
        "discipline": 4,
        "confidence": 2
      },
      "technical": "Sector rotation out of tech hurt the names I was long despite individual chart being clean.",
      "other": ""
    },
    "duration": 149
  },
  {
    "openDate": "2026-01-22T14:17:00.000Z",
    "closeDate": "2026-01-22T16:38:00.000Z",
    "timeframe": "1m",
    "pair": "AMD",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": false
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 55,
    "result": "Win",
    "rr": 3.51,
    "sl": 3.91,
    "tp": 13.71,
    "pnl": 702.77,
    "netPnl": 702.49,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 3,
        "patience": 5,
        "discipline": 2,
        "confidence": 2
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 141
  },
  {
    "openDate": "2026-01-22T14:56:00.000Z",
    "closeDate": "2026-01-22T16:54:00.000Z",
    "timeframe": "5m",
    "pair": "AMZN",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 56,
    "result": "Loss",
    "rr": 0.85,
    "sl": 1.3,
    "tp": 1.1,
    "pnl": -65.96,
    "netPnl": -66.24,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Bought the top of a news spike. Classic FOMO — always wait for confirmation.",
        "fomo": 5,
        "patience": 1,
        "discipline": 3,
        "confidence": 1
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 118
  },
  {
    "openDate": "2026-01-22T13:12:00.000Z",
    "closeDate": "2026-01-22T13:50:00.000Z",
    "timeframe": "5m",
    "pair": "META",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 22,
    "result": "Win",
    "rr": 1.45,
    "sl": 4.73,
    "tp": 6.86,
    "pnl": 138.54,
    "netPnl": 138.43,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 4,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 38
  },
  {
    "openDate": "2026-01-23T10:44:00.000Z",
    "closeDate": "2026-01-23T11:44:00.000Z",
    "timeframe": "5m",
    "pair": "NVDA",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": false,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 63,
    "result": "Loss",
    "rr": 0.5,
    "sl": 4.81,
    "tp": 2.4,
    "pnl": -262.87,
    "netPnl": -263.19,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Chased the open gap, no patience for a pullback entry. Paid for it.",
        "fomo": 4,
        "patience": 1,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 60
  },
  {
    "openDate": "2026-01-23T11:46:00.000Z",
    "closeDate": "2026-01-23T12:05:00.000Z",
    "timeframe": "1H",
    "pair": "QQQ",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": false
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 73,
    "result": "Win",
    "rr": 2.09,
    "sl": 2.99,
    "tp": 6.25,
    "pnl": 419.75,
    "netPnl": 419.39,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "VWAP reclaim right at the open — beautiful entry. Let the trade run to +2R.",
        "fomo": 2,
        "patience": 2,
        "discipline": 2,
        "confidence": 4
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 19
  },
  {
    "openDate": "2026-01-26T10:41:00.000Z",
    "closeDate": "2026-01-26T14:31:00.000Z",
    "timeframe": "1D",
    "pair": "MSFT",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": false,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": false
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 25,
    "result": "Loss",
    "rr": 1.06,
    "sl": 1.29,
    "tp": 1.36,
    "pnl": -30.24,
    "netPnl": -30.37,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Sold into panic — stop was hit exactly at the LOD which reversed. Review stop placement.",
        "fomo": 5,
        "patience": 1,
        "discipline": 3,
        "confidence": 3
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 230
  },
  {
    "openDate": "2026-01-26T13:20:00.000Z",
    "closeDate": "2026-01-26T15:53:00.000Z",
    "timeframe": "1H",
    "pair": "AMZN",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 59,
    "result": "Win",
    "rr": 2.42,
    "sl": 0.64,
    "tp": 1.54,
    "pnl": 88.86,
    "netPnl": 88.57,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 3,
        "patience": 5,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 153
  },
  {
    "openDate": "2026-01-27T14:16:00.000Z",
    "closeDate": "2026-01-27T15:17:00.000Z",
    "timeframe": "15m",
    "pair": "MSFT",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 16,
    "result": "Win",
    "rr": 1.61,
    "sl": 2.55,
    "tp": 4.1,
    "pnl": 63.76,
    "netPnl": 63.68,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 3,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 61
  },
  {
    "openDate": "2026-01-27T09:30:00.000Z",
    "closeDate": "2026-01-27T10:07:00.000Z",
    "timeframe": "1m",
    "pair": "NVDA",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 56,
    "result": "Win",
    "rr": 2.06,
    "sl": 4.16,
    "tp": 8.57,
    "pnl": 421.37,
    "netPnl": 421.09,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 2,
        "patience": 2,
        "discipline": 3,
        "confidence": 4
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 37
  },
  {
    "openDate": "2026-01-28T11:54:00.000Z",
    "closeDate": "2026-01-28T12:28:00.000Z",
    "timeframe": "1m",
    "pair": "AAPL",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": false,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 16,
    "result": "Win",
    "rr": 3.26,
    "sl": 2.84,
    "tp": 9.25,
    "pnl": 129.94,
    "netPnl": 129.86,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 1,
        "patience": 4,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 34
  },
  {
    "openDate": "2026-01-29T13:29:00.000Z",
    "closeDate": "2026-01-29T15:27:00.000Z",
    "timeframe": "1m",
    "pair": "AMD",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": false,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 61,
    "result": "Loss",
    "rr": 0.51,
    "sl": 3.67,
    "tp": 1.87,
    "pnl": -207.42,
    "netPnl": -207.72,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Chased the open gap, no patience for a pullback entry. Paid for it.",
        "fomo": 3,
        "patience": 1,
        "discipline": 1,
        "confidence": 2
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 118
  },
  {
    "openDate": "2026-01-29T11:15:00.000Z",
    "closeDate": "2026-01-29T12:56:00.000Z",
    "timeframe": "5m",
    "pair": "QQQ",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 23,
    "result": "Win",
    "rr": 3.57,
    "sl": 3.08,
    "tp": 11,
    "pnl": 231.24,
    "netPnl": 231.12,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 4,
        "patience": 2,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 101
  },
  {
    "openDate": "2026-01-29T10:59:00.000Z",
    "closeDate": "2026-01-29T14:45:00.000Z",
    "timeframe": "1D",
    "pair": "AMD",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": false
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 29,
    "result": "Win",
    "rr": 2.49,
    "sl": 4.91,
    "tp": 12.24,
    "pnl": 310.94,
    "netPnl": 310.8,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 3,
        "patience": 3,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 226
  },
  {
    "openDate": "2026-01-30T10:39:00.000Z",
    "closeDate": "2026-01-30T14:16:00.000Z",
    "timeframe": "1m",
    "pair": "AMZN",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": false,
      "Revenue beat?": true,
      "Guidance raised?": false,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 63,
    "result": "Break Even",
    "rr": 0.94,
    "sl": 2.12,
    "tp": 1.99,
    "pnl": 8.64,
    "netPnl": 8.32,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved to break-even when I saw the 5-min bar stall. Missed the rest of the move.",
        "fomo": 3,
        "patience": 3,
        "discipline": 2,
        "confidence": 2
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 217
  },
  {
    "openDate": "2026-02-02T14:34:00.000Z",
    "closeDate": "2026-02-02T15:07:00.000Z",
    "timeframe": "1H",
    "pair": "AMD",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": false,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 44,
    "result": "Win",
    "rr": 2.6,
    "sl": 2.77,
    "tp": 7.21,
    "pnl": 308.99,
    "netPnl": 308.77,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 4,
        "patience": 2,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "AMD made a clean higher low above VWAP, entered on micro breakout, target hit in 45 mins.",
      "other": ""
    },
    "duration": 33
  },
  {
    "openDate": "2026-02-02T15:05:00.000Z",
    "closeDate": "2026-02-02T15:40:00.000Z",
    "timeframe": "15m",
    "pair": "SPY",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 41,
    "result": "Win",
    "rr": 2.25,
    "sl": 2.45,
    "tp": 5.51,
    "pnl": 201.51,
    "netPnl": 201.3,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "VWAP reclaim right at the open — beautiful entry. Let the trade run to +2R.",
        "fomo": 2,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 35
  },
  {
    "openDate": "2026-02-03T13:07:00.000Z",
    "closeDate": "2026-02-03T14:27:00.000Z",
    "timeframe": "1m",
    "pair": "MSFT",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 5,
    "result": "Win",
    "rr": 2.26,
    "sl": 2.42,
    "tp": 5.47,
    "pnl": 26.83,
    "netPnl": 26.8,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 3,
        "patience": 2,
        "discipline": 5,
        "confidence": 4
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 80
  },
  {
    "openDate": "2026-02-04T14:10:00.000Z",
    "closeDate": "2026-02-04T14:29:00.000Z",
    "timeframe": "5m",
    "pair": "MSFT",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 64,
    "result": "Loss",
    "rr": 1.06,
    "sl": 0.97,
    "tp": 1.03,
    "pnl": -61.4,
    "netPnl": -61.72,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Sold into panic — stop was hit exactly at the LOD which reversed. Review stop placement.",
        "fomo": 5,
        "patience": 4,
        "discipline": 4,
        "confidence": 2
      },
      "technical": "META earnings-day gap up, waited 15 mins, entered the bull-flag breakout at open range high.",
      "other": ""
    },
    "duration": 19
  },
  {
    "openDate": "2026-02-04T15:22:00.000Z",
    "closeDate": "2026-02-04T16:29:00.000Z",
    "timeframe": "1m",
    "pair": "AMZN",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 34,
    "result": "Loss",
    "rr": 0.51,
    "sl": 2.76,
    "tp": 1.41,
    "pnl": -92.2,
    "netPnl": -92.37,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Overtraded — took 4 trades, all small losses that added up. Should have stopped after 2.",
        "fomo": 4,
        "patience": 1,
        "discipline": 2,
        "confidence": 3
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 67
  },
  {
    "openDate": "2026-02-05T11:40:00.000Z",
    "closeDate": "2026-02-05T13:06:00.000Z",
    "timeframe": "1D",
    "pair": "AMD",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 32,
    "result": "Win",
    "rr": 3.81,
    "sl": 2.14,
    "tp": 8.16,
    "pnl": 248.85,
    "netPnl": 248.69,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "VWAP reclaim right at the open — beautiful entry. Let the trade run to +2R.",
        "fomo": 2,
        "patience": 4,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 86
  },
  {
    "openDate": "2026-02-06T11:56:00.000Z",
    "closeDate": "2026-02-06T15:14:00.000Z",
    "timeframe": "1D",
    "pair": "AMZN",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": false,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 32,
    "result": "Win",
    "rr": 3.62,
    "sl": 2.72,
    "tp": 9.84,
    "pnl": 296.93,
    "netPnl": 296.77,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 3,
        "patience": 5,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 198
  },
  {
    "openDate": "2026-02-09T10:13:00.000Z",
    "closeDate": "2026-02-09T12:26:00.000Z",
    "timeframe": "1D",
    "pair": "NVDA",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 68,
    "result": "Win",
    "rr": 1.58,
    "sl": 5.85,
    "tp": 9.25,
    "pnl": 555.41,
    "netPnl": 555.07,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Earnings play worked as expected. Sizing was conservative — left money but protected capital.",
        "fomo": 3,
        "patience": 2,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 133
  },
  {
    "openDate": "2026-02-09T09:32:00.000Z",
    "closeDate": "2026-02-09T11:27:00.000Z",
    "timeframe": "1H",
    "pair": "META",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": false,
      "Entry within 2% of breakout level?": false
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 59,
    "result": "Win",
    "rr": 2.22,
    "sl": 3.08,
    "tp": 6.84,
    "pnl": 386.61,
    "netPnl": 386.32,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Caught the morning momentum perfectly. Held my planned size and didn't add impulsively.",
        "fomo": 4,
        "patience": 3,
        "discipline": 5,
        "confidence": 4
      },
      "technical": "QQQ breakout above 3-month ascending triangle. Entered on retest, hit measured target.",
      "other": ""
    },
    "duration": 115
  },
  {
    "openDate": "2026-02-10T12:29:00.000Z",
    "closeDate": "2026-02-10T13:28:00.000Z",
    "timeframe": "15m",
    "pair": "GOOGL",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": false,
      "ATR expanding into breakout?": false,
      "Stop below breakout candle low?": false,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 34,
    "result": "Break Even",
    "rr": 1.04,
    "sl": 1.82,
    "tp": 1.9,
    "pnl": -1.81,
    "netPnl": -1.98,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved to break-even when I saw the 5-min bar stall. Missed the rest of the move.",
        "fomo": 1,
        "patience": 4,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 59
  },
  {
    "openDate": "2026-02-10T11:43:00.000Z",
    "closeDate": "2026-02-10T13:06:00.000Z",
    "timeframe": "5m",
    "pair": "MSFT",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 58,
    "result": "Win",
    "rr": 3.22,
    "sl": 1.17,
    "tp": 3.77,
    "pnl": 197.01,
    "netPnl": 196.72,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 3,
        "patience": 5,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 83
  },
  {
    "openDate": "2026-02-11T14:44:00.000Z",
    "closeDate": "2026-02-11T17:24:00.000Z",
    "timeframe": "1D",
    "pair": "AMD",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 53,
    "result": "Win",
    "rr": 3.21,
    "sl": 5.76,
    "tp": 18.49,
    "pnl": 855.51,
    "netPnl": 855.24,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 2,
        "patience": 3,
        "discipline": 5,
        "confidence": 5
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 160
  },
  {
    "openDate": "2026-02-11T12:14:00.000Z",
    "closeDate": "2026-02-11T14:25:00.000Z",
    "timeframe": "1m",
    "pair": "TSLA",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": false,
      "Waited for first 5-min candle to close?": false,
      "Stop below gap level?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 39,
    "result": "Loss",
    "rr": 0.63,
    "sl": 7.77,
    "tp": 4.9,
    "pnl": -269.53,
    "netPnl": -269.73,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Sold into panic — stop was hit exactly at the LOD which reversed. Review stop placement.",
        "fomo": 5,
        "patience": 4,
        "discipline": 2,
        "confidence": 1
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 131
  },
  {
    "openDate": "2026-02-12T14:13:00.000Z",
    "closeDate": "2026-02-12T17:59:00.000Z",
    "timeframe": "15m",
    "pair": "QQQ",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": false,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 55,
    "result": "Break Even",
    "rr": 1.26,
    "sl": 1.99,
    "tp": 2.51,
    "pnl": -3.07,
    "netPnl": -3.35,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Scratched it early — news headline came out and I wasn't sure of direction.",
        "fomo": 3,
        "patience": 5,
        "discipline": 2,
        "confidence": 5
      },
      "technical": "Setup looked clean on the 5m but daily showed clear resistance just above entry.",
      "other": ""
    },
    "duration": 226
  },
  {
    "openDate": "2026-02-12T15:01:00.000Z",
    "closeDate": "2026-02-12T15:46:00.000Z",
    "timeframe": "1H",
    "pair": "MSFT",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": false,
      "Market internals bullish?": false,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 24,
    "result": "Break Even",
    "rr": 1.21,
    "sl": 1.99,
    "tp": 2.41,
    "pnl": 15.62,
    "netPnl": 15.5,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Scratched it early — news headline came out and I wasn't sure of direction.",
        "fomo": 3,
        "patience": 3,
        "discipline": 3,
        "confidence": 2
      },
      "technical": "AAPL formed an inside day then broke higher on iPhone unit beat. Held through pullback.",
      "other": ""
    },
    "duration": 45
  },
  {
    "openDate": "2026-02-12T14:03:00.000Z",
    "closeDate": "2026-02-12T15:57:00.000Z",
    "timeframe": "1H",
    "pair": "MSFT",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": false,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 3,
    "lots": 66,
    "result": "Win",
    "rr": 3.46,
    "sl": 0.55,
    "tp": 1.9,
    "pnl": 111.23,
    "netPnl": 110.9,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 3,
        "patience": 4,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "META earnings-day gap up, waited 15 mins, entered the bull-flag breakout at open range high.",
      "other": ""
    },
    "duration": 114
  },
  {
    "openDate": "2026-02-13T15:24:00.000Z",
    "closeDate": "2026-02-13T19:17:00.000Z",
    "timeframe": "1m",
    "pair": "MSFT",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": true,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 42,
    "result": "Win",
    "rr": 2.63,
    "sl": 2.93,
    "tp": 7.69,
    "pnl": 322.33,
    "netPnl": 322.12,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Pre-market scan highlighted this the night before. Setup was perfect at open.",
        "fomo": 4,
        "patience": 5,
        "discipline": 5,
        "confidence": 4
      },
      "technical": "META earnings-day gap up, waited 15 mins, entered the bull-flag breakout at open range high.",
      "other": ""
    },
    "duration": 233
  },
  {
    "openDate": "2026-02-13T11:45:00.000Z",
    "closeDate": "2026-02-13T14:54:00.000Z",
    "timeframe": "1m",
    "pair": "SPY",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": true,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 61,
    "result": "Win",
    "rr": 2.74,
    "sl": 0.65,
    "tp": 1.78,
    "pnl": 95.33,
    "netPnl": 95.03,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Caught the morning momentum perfectly. Held my planned size and didn't add impulsively.",
        "fomo": 4,
        "patience": 3,
        "discipline": 5,
        "confidence": 2
      },
      "technical": "META earnings-day gap up, waited 15 mins, entered the bull-flag breakout at open range high.",
      "other": ""
    },
    "duration": 189
  },
  {
    "openDate": "2026-02-13T13:54:00.000Z",
    "closeDate": "2026-02-13T16:06:00.000Z",
    "timeframe": "15m",
    "pair": "QQQ",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 59,
    "result": "Win",
    "rr": 3.96,
    "sl": 3.63,
    "tp": 14.37,
    "pnl": 841.9,
    "netPnl": 841.61,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Caught the morning momentum perfectly. Held my planned size and didn't add impulsively.",
        "fomo": 4,
        "patience": 5,
        "discipline": 2,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 132
  },
  {
    "openDate": "2026-02-16T15:04:00.000Z",
    "closeDate": "2026-02-16T15:18:00.000Z",
    "timeframe": "15m",
    "pair": "TSLA",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 17,
    "result": "Loss",
    "rr": 1.28,
    "sl": 1.91,
    "tp": 2.44,
    "pnl": -32.29,
    "netPnl": -32.38,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Chased the open gap, no patience for a pullback entry. Paid for it.",
        "fomo": 5,
        "patience": 1,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "Setup looked clean on the 5m but daily showed clear resistance just above entry.",
      "other": ""
    },
    "duration": 14
  },
  {
    "openDate": "2026-02-17T11:41:00.000Z",
    "closeDate": "2026-02-17T12:44:00.000Z",
    "timeframe": "15m",
    "pair": "GOOGL",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 47,
    "result": "Win",
    "rr": 2.48,
    "sl": 0.65,
    "tp": 1.61,
    "pnl": 75.52,
    "netPnl": 75.28,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 4,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 63
  },
  {
    "openDate": "2026-02-17T10:30:00.000Z",
    "closeDate": "2026-02-17T12:04:00.000Z",
    "timeframe": "1H",
    "pair": "AMZN",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": false,
      "Revenue beat?": true,
      "Guidance raised?": true,
      "Waited for gap-and-go confirmation?": true,
      "Avoided chasing > 5% from open?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 27,
    "result": "Win",
    "rr": 1.76,
    "sl": 3.76,
    "tp": 6.61,
    "pnl": 152.06,
    "netPnl": 151.92,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Caught the morning momentum perfectly. Held my planned size and didn't add impulsively.",
        "fomo": 1,
        "patience": 5,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 94
  },
  {
    "openDate": "2026-02-18T13:48:00.000Z",
    "closeDate": "2026-02-18T17:10:00.000Z",
    "timeframe": "1D",
    "pair": "AMD",
    "strategy": "Earnings Play",
    "checklistAnswers": {
      "EPS beat > 5%?": false,
      "Revenue beat?": true,
      "Guidance raised?": false,
      "Waited for gap-and-go confirmation?": false,
      "Avoided chasing > 5% from open?": false
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 25,
    "result": "Loss",
    "rr": 0.91,
    "sl": 4.72,
    "tp": 4.29,
    "pnl": -109.18,
    "netPnl": -109.31,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Overtraded — took 4 trades, all small losses that added up. Should have stopped after 2.",
        "fomo": 5,
        "patience": 2,
        "discipline": 1,
        "confidence": 2
      },
      "technical": "Opened at key support, bounced briefly, then broke down. Was too early on the long.",
      "other": ""
    },
    "duration": 202
  },
  {
    "openDate": "2026-02-19T15:06:00.000Z",
    "closeDate": "2026-02-19T16:28:00.000Z",
    "timeframe": "15m",
    "pair": "QQQ",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": false
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 22,
    "result": "Win",
    "rr": 3.89,
    "sl": 3.04,
    "tp": 11.81,
    "pnl": 251.77,
    "netPnl": 251.66,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 3,
        "patience": 3,
        "discipline": 3,
        "confidence": 5
      },
      "technical": "AAPL formed an inside day then broke higher on iPhone unit beat. Held through pullback.",
      "other": ""
    },
    "duration": 82
  },
  {
    "openDate": "2026-02-19T15:18:00.000Z",
    "closeDate": "2026-02-19T16:33:00.000Z",
    "timeframe": "1m",
    "pair": "AAPL",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": true,
      "Size risk ≤ 1% of account?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 61,
    "result": "Win",
    "rr": 2.1,
    "sl": 1.71,
    "tp": 3.58,
    "pnl": 194.79,
    "netPnl": 194.49,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "VWAP reclaim right at the open — beautiful entry. Let the trade run to +2R.",
        "fomo": 5,
        "patience": 3,
        "discipline": 4,
        "confidence": 4
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 75
  },
  {
    "openDate": "2026-02-20T13:06:00.000Z",
    "closeDate": "2026-02-20T15:19:00.000Z",
    "timeframe": "1H",
    "pair": "QQQ",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": false,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Sell",
    "tradeNumber": 1,
    "lots": 17,
    "result": "Break Even",
    "rr": 0.73,
    "sl": 2.43,
    "tp": 1.77,
    "pnl": 3.68,
    "netPnl": 3.59,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Moved to break-even when I saw the 5-min bar stall. Missed the rest of the move.",
        "fomo": 4,
        "patience": 5,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "QQQ breakout above 3-month ascending triangle. Entered on retest, hit measured target.",
      "other": ""
    },
    "duration": 133
  },
  {
    "openDate": "2026-02-23T15:56:00.000Z",
    "closeDate": "2026-02-23T19:29:00.000Z",
    "timeframe": "15m",
    "pair": "META",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": false
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 31,
    "result": "Loss",
    "rr": 1.29,
    "sl": 4.13,
    "tp": 5.33,
    "pnl": -109.08,
    "netPnl": -109.23,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Sold into panic — stop was hit exactly at the LOD which reversed. Review stop placement.",
        "fomo": 5,
        "patience": 1,
        "discipline": 3,
        "confidence": 2
      },
      "technical": "Setup looked clean on the 5m but daily showed clear resistance just above entry.",
      "other": ""
    },
    "duration": 213
  },
  {
    "openDate": "2026-02-25T09:25:00.000Z",
    "closeDate": "2026-02-25T12:06:00.000Z",
    "timeframe": "1D",
    "pair": "GOOGL",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 29,
    "result": "Win",
    "rr": 1.51,
    "sl": 4.02,
    "tp": 6.07,
    "pnl": 151.03,
    "netPnl": 150.89,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Caught the morning momentum perfectly. Held my planned size and didn't add impulsively.",
        "fomo": 5,
        "patience": 3,
        "discipline": 5,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 161
  },
  {
    "openDate": "2026-02-25T12:27:00.000Z",
    "closeDate": "2026-02-25T14:51:00.000Z",
    "timeframe": "1m",
    "pair": "META",
    "strategy": "Momentum",
    "checklistAnswers": {
      "Price above 20-day EMA?": true,
      "Volume expanding on breakout?": true,
      "RSI < 70 on entry?": true,
      "Entry within 2% of breakout level?": true
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 9,
    "result": "Win",
    "rr": 1.46,
    "sl": 4,
    "tp": 5.85,
    "pnl": 48.33,
    "netPnl": 48.29,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Stuck to the plan, no adjustments once in. Discipline paid off today.",
        "fomo": 2,
        "patience": 2,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 144
  },
  {
    "openDate": "2026-02-26T10:30:00.000Z",
    "closeDate": "2026-02-26T12:50:00.000Z",
    "timeframe": "5m",
    "pair": "TSLA",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 21,
    "result": "Win",
    "rr": 3.61,
    "sl": 5.75,
    "tp": 20.76,
    "pnl": 422.45,
    "netPnl": 422.35,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "VWAP reclaim right at the open — beautiful entry. Let the trade run to +2R.",
        "fomo": 1,
        "patience": 3,
        "discipline": 4,
        "confidence": 5
      },
      "technical": "TSLA gap filled from $360 back to $372 pre-market level. Textbook morning reversal.",
      "other": ""
    },
    "duration": 140
  },
  {
    "openDate": "2026-02-26T11:05:00.000Z",
    "closeDate": "2026-02-26T12:17:00.000Z",
    "timeframe": "15m",
    "pair": "META",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": false,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": false,
      "Size risk ≤ 1% of account?": false
    },
    "direction": "Buy",
    "tradeNumber": 2,
    "lots": 32,
    "result": "Loss",
    "rr": 0.72,
    "sl": 3.22,
    "tp": 2.32,
    "pnl": -101.08,
    "netPnl": -101.24,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Earnings missed badly. I had too large a position for the uncertainty involved.",
        "fomo": 5,
        "patience": 1,
        "discipline": 3,
        "confidence": 3
      },
      "technical": "Opened at key support, bounced briefly, then broke down. Was too early on the long.",
      "other": ""
    },
    "duration": 72
  },
  {
    "openDate": "2026-02-26T13:04:00.000Z",
    "closeDate": "2026-02-26T15:44:00.000Z",
    "timeframe": "1H",
    "pair": "AAPL",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": false,
      "Market internals bullish?": false,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": false
    },
    "direction": "Buy",
    "tradeNumber": 3,
    "lots": 79,
    "result": "Break Even",
    "rr": 1.24,
    "sl": 0.48,
    "tp": 0.6,
    "pnl": -3.47,
    "netPnl": -3.87,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Scratched it early — news headline came out and I wasn't sure of direction.",
        "fomo": 5,
        "patience": 1,
        "discipline": 4,
        "confidence": 3
      },
      "technical": "AMD made a clean higher low above VWAP, entered on micro breakout, target hit in 45 mins.",
      "other": ""
    },
    "duration": 160
  },
  {
    "openDate": "2026-02-27T14:02:00.000Z",
    "closeDate": "2026-02-27T15:39:00.000Z",
    "timeframe": "1D",
    "pair": "AAPL",
    "strategy": "Breakout",
    "checklistAnswers": {
      "Clear multi-day consolidation present?": true,
      "ATR expanding into breakout?": true,
      "Stop below breakout candle low?": false,
      "Size risk ≤ 1% of account?": false
    },
    "direction": "Buy",
    "tradeNumber": 1,
    "lots": 24,
    "result": "Win",
    "rr": 3.67,
    "sl": 1.84,
    "tp": 6.74,
    "pnl": 139.44,
    "netPnl": 139.32,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 2,
        "patience": 5,
        "discipline": 5,
        "confidence": 3
      },
      "technical": "NVDA broke above the 3-week balance area at $140 with 3x normal volume. Clean measured move.",
      "other": ""
    },
    "duration": 97
  },
  {
    "openDate": "2026-02-27T11:20:00.000Z",
    "closeDate": "2026-02-27T14:28:00.000Z",
    "timeframe": "1m",
    "pair": "META",
    "strategy": "VWAP Reclaim",
    "checklistAnswers": {
      "Price dipped below VWAP and reclaimed?": true,
      "Market internals bullish?": true,
      "Entry on first retest of VWAP from above?": true,
      "Volume confirming?": true
    },
    "direction": "Sell",
    "tradeNumber": 2,
    "lots": 21,
    "result": "Win",
    "rr": 3.5,
    "sl": 4.16,
    "tp": 14.55,
    "pnl": 292.41,
    "netPnl": 292.31,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Only took the A+ setup. Said no to 3 mediocre setups and hit a home run on the one I took.",
        "fomo": 2,
        "patience": 3,
        "discipline": 2,
        "confidence": 5
      },
      "technical": "SPY reclaimed VWAP at 10:30am after initial flush. Strong buying through R1 pivot.",
      "other": ""
    },
    "duration": 188
  },
  {
    "openDate": "2026-02-27T15:01:00.000Z",
    "closeDate": "2026-02-27T16:03:00.000Z",
    "timeframe": "1H",
    "pair": "AMD",
    "strategy": "Gap Fill",
    "checklistAnswers": {
      "Gap > 1.5% at open?": false,
      "Pre-market volume > 2x average?": true,
      "Waited for first 5-min candle to close?": true,
      "Stop below gap level?": true
    },
    "direction": "Sell",
    "tradeNumber": 3,
    "lots": 70,
    "result": "Win",
    "rr": 3.36,
    "sl": 5.99,
    "tp": 20.14,
    "pnl": 1208.2,
    "netPnl": 1207.85,
    "screenshotUrl": "",
    "notes": {
      "emotion": {
        "text": "Gap-and-go setup worked like a textbook. Exited at the pre-planned measured move.",
        "fomo": 1,
        "patience": 3,
        "discipline": 3,
        "confidence": 5
      },
      "technical": "MSFT touched the rising 20-day EMA and bounced with strong candle. Held to prior high.",
      "other": ""
    },
    "duration": 62
  }
];
}

export function getSeedStocksMoods(): SeedMood[] {
  return [
  {
    "date": "2026-01-02",
    "moodScore": 3,
    "energyLevel": 66,
    "stressLevel": 74,
    "sleepHours": 5.7,
    "dietScore": "Clean",
    "caffeineIntake": "None",
    "exercised": false,
    "notes": "Strong sector rotation into tech. Lots of opportunity but staying disciplined."
  },
  {
    "date": "2026-01-05",
    "moodScore": 4,
    "energyLevel": 70,
    "stressLevel": 60,
    "sleepHours": 8.1,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "New quarter starting. Reviewing last quarter's stats and setting fresh targets."
  },
  {
    "date": "2026-01-06",
    "moodScore": 4,
    "energyLevel": 45,
    "stressLevel": 28,
    "sleepHours": 6.3,
    "dietScore": "Clean",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Reviewed my monthly stats. Win rate 62%, need to work on avg winner size."
  },
  {
    "date": "2026-01-07",
    "moodScore": 4,
    "energyLevel": 60,
    "stressLevel": 44,
    "sleepHours": 7.8,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Reviewed 5 trades from last week. Found a clear pattern — I overtrade on Mondays."
  },
  {
    "date": "2026-01-08",
    "moodScore": 3,
    "energyLevel": 78,
    "stressLevel": 61,
    "sleepHours": 8.3,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "New quarter starting. Reviewing last quarter's stats and setting fresh targets."
  },
  {
    "date": "2026-01-09",
    "moodScore": 4,
    "energyLevel": 49,
    "stressLevel": 21,
    "sleepHours": 7.5,
    "dietScore": "Moderate",
    "caffeineIntake": "None",
    "exercised": false,
    "notes": "Fed day — volatility expected. Half position sizes across the board."
  },
  {
    "date": "2026-01-12",
    "moodScore": 4,
    "energyLevel": 56,
    "stressLevel": 47,
    "sleepHours": 6.4,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Two red days in a row. Focusing on the process, not the P&L."
  },
  {
    "date": "2026-01-13",
    "moodScore": 2,
    "energyLevel": 80,
    "stressLevel": 77,
    "sleepHours": 7.8,
    "dietScore": "Moderate",
    "caffeineIntake": "3+ cups",
    "exercised": true,
    "notes": "Market opened choppy. Took one trade, scratched it, stopped for the day."
  },
  {
    "date": "2026-01-14",
    "moodScore": 5,
    "energyLevel": 73,
    "stressLevel": 35,
    "sleepHours": 6.3,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Reviewed 5 trades from last week. Found a clear pattern — I overtrade on Mondays."
  },
  {
    "date": "2026-01-15",
    "moodScore": 3,
    "energyLevel": 36,
    "stressLevel": 28,
    "sleepHours": 6.8,
    "dietScore": "Moderate",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Market opened choppy. Took one trade, scratched it, stopped for the day."
  },
  {
    "date": "2026-01-16",
    "moodScore": 4,
    "energyLevel": 81,
    "stressLevel": 19,
    "sleepHours": 7.9,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Fed day — volatility expected. Half position sizes across the board."
  },
  {
    "date": "2026-01-19",
    "moodScore": 4,
    "energyLevel": 59,
    "stressLevel": 22,
    "sleepHours": 5.8,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Market opened choppy. Took one trade, scratched it, stopped for the day."
  },
  {
    "date": "2026-01-20",
    "moodScore": 2,
    "energyLevel": 78,
    "stressLevel": 60,
    "sleepHours": 7,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Missed the morning session. Only two afternoon setups — took neither."
  },
  {
    "date": "2026-01-21",
    "moodScore": 5,
    "energyLevel": 63,
    "stressLevel": 31,
    "sleepHours": 6.5,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Reviewed my monthly stats. Win rate 62%, need to work on avg winner size."
  },
  {
    "date": "2026-01-22",
    "moodScore": 5,
    "energyLevel": 62,
    "stressLevel": 15,
    "sleepHours": 6.1,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Monthly close. Expect institutional rebalancing flows. Patience."
  },
  {
    "date": "2026-01-23",
    "moodScore": 4,
    "energyLevel": 46,
    "stressLevel": 60,
    "sleepHours": 8.2,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Fed day — volatility expected. Half position sizes across the board."
  },
  {
    "date": "2026-01-26",
    "moodScore": 4,
    "energyLevel": 56,
    "stressLevel": 21,
    "sleepHours": 5.9,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Pre-market prep done. Watchlist set, key levels marked. Feel ready."
  },
  {
    "date": "2026-01-27",
    "moodScore": 4,
    "energyLevel": 43,
    "stressLevel": 62,
    "sleepHours": 7.7,
    "dietScore": "Moderate",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Options expiry Friday. Expecting pinning behaviour — avoiding complex plays."
  },
  {
    "date": "2026-01-28",
    "moodScore": 5,
    "energyLevel": 54,
    "stressLevel": 9,
    "sleepHours": 7.9,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Earnings season in full swing. Only trading post-earnings breakdowns with confirmation."
  },
  {
    "date": "2026-01-29",
    "moodScore": 5,
    "energyLevel": 86,
    "stressLevel": 53,
    "sleepHours": 8.3,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Options expiry Friday. Expecting pinning behaviour — avoiding complex plays."
  },
  {
    "date": "2026-01-30",
    "moodScore": 4,
    "energyLevel": 85,
    "stressLevel": 45,
    "sleepHours": 7.7,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Slept 7 hours. Clear head going into earnings season."
  },
  {
    "date": "2026-02-02",
    "moodScore": 5,
    "energyLevel": 100,
    "stressLevel": 21,
    "sleepHours": 6,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Partner distracted me during a key entry. Need to improve my trading environment."
  },
  {
    "date": "2026-02-03",
    "moodScore": 3,
    "energyLevel": 82,
    "stressLevel": 23,
    "sleepHours": 7.3,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Reached my weekly profit target by Wednesday. Finishing early to avoid giving it back."
  },
  {
    "date": "2026-02-04",
    "moodScore": 3,
    "energyLevel": 44,
    "stressLevel": 30,
    "sleepHours": 7.3,
    "dietScore": "Moderate",
    "caffeineIntake": "3+ cups",
    "exercised": true,
    "notes": "Pre-market prep done. Watchlist set, key levels marked. Feel ready."
  },
  {
    "date": "2026-02-05",
    "moodScore": 4,
    "energyLevel": 78,
    "stressLevel": 14,
    "sleepHours": 6.9,
    "dietScore": "Moderate",
    "caffeineIntake": "3+ cups",
    "exercised": false,
    "notes": "Macro: CPI print came in hot. Risk-off sentiment. Only shorting today."
  },
  {
    "date": "2026-02-06",
    "moodScore": 5,
    "energyLevel": 64,
    "stressLevel": 16,
    "sleepHours": 7.1,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Reviewed my monthly stats. Win rate 62%, need to work on avg winner size."
  },
  {
    "date": "2026-02-09",
    "moodScore": 5,
    "energyLevel": 95,
    "stressLevel": 22,
    "sleepHours": 7.8,
    "dietScore": "Clean",
    "caffeineIntake": "3+ cups",
    "exercised": true,
    "notes": "Tired after late night. Will only take the most obvious setups today."
  },
  {
    "date": "2026-02-10",
    "moodScore": 3,
    "energyLevel": 56,
    "stressLevel": 71,
    "sleepHours": 6.7,
    "dietScore": "Moderate",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Journalled last night's trades. Found I exit winners 2x too early. Working on it."
  },
  {
    "date": "2026-02-11",
    "moodScore": 4,
    "energyLevel": 43,
    "stressLevel": 30,
    "sleepHours": 7.6,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Slept 7 hours. Clear head going into earnings season."
  },
  {
    "date": "2026-02-12",
    "moodScore": 3,
    "energyLevel": 81,
    "stressLevel": 47,
    "sleepHours": 8.3,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Two red days in a row. Focusing on the process, not the P&L."
  },
  {
    "date": "2026-02-13",
    "moodScore": 4,
    "energyLevel": 74,
    "stressLevel": 18,
    "sleepHours": 5.6,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Reviewed 5 trades from last week. Found a clear pattern — I overtrade on Mondays."
  },
  {
    "date": "2026-02-16",
    "moodScore": 4,
    "energyLevel": 95,
    "stressLevel": 25,
    "sleepHours": 8.3,
    "dietScore": "Moderate",
    "caffeineIntake": "3+ cups",
    "exercised": true,
    "notes": "Strong sector rotation into tech. Lots of opportunity but staying disciplined."
  },
  {
    "date": "2026-02-17",
    "moodScore": 3,
    "energyLevel": 37,
    "stressLevel": 39,
    "sleepHours": 6,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "New quarter starting. Reviewing last quarter's stats and setting fresh targets."
  },
  {
    "date": "2026-02-18",
    "moodScore": 2,
    "energyLevel": 44,
    "stressLevel": 49,
    "sleepHours": 7.5,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "1-2 cups",
    "exercised": true,
    "notes": "Monthly close. Expect institutional rebalancing flows. Patience."
  },
  {
    "date": "2026-02-19",
    "moodScore": 4,
    "energyLevel": 52,
    "stressLevel": 39,
    "sleepHours": 7,
    "dietScore": "Moderate",
    "caffeineIntake": "3+ cups",
    "exercised": false,
    "notes": "Reviewed my monthly stats. Win rate 62%, need to work on avg winner size."
  },
  {
    "date": "2026-02-20",
    "moodScore": 5,
    "energyLevel": 64,
    "stressLevel": 33,
    "sleepHours": 6.4,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Slept 7 hours. Clear head going into earnings season."
  },
  {
    "date": "2026-02-23",
    "moodScore": 2,
    "energyLevel": 71,
    "stressLevel": 48,
    "sleepHours": 5.9,
    "dietScore": "Clean",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Reviewed 5 trades from last week. Found a clear pattern — I overtrade on Mondays."
  },
  {
    "date": "2026-02-24",
    "moodScore": 4,
    "energyLevel": 51,
    "stressLevel": 60,
    "sleepHours": 7.2,
    "dietScore": "Clean",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Reviewed 5 trades from last week. Found a clear pattern — I overtrade on Mondays."
  },
  {
    "date": "2026-02-25",
    "moodScore": 3,
    "energyLevel": 76,
    "stressLevel": 68,
    "sleepHours": 8.1,
    "dietScore": "Clean",
    "caffeineIntake": "3+ cups",
    "exercised": true,
    "notes": "Pre-market prep done. Watchlist set, key levels marked. Feel ready."
  },
  {
    "date": "2026-02-26",
    "moodScore": 5,
    "energyLevel": 58,
    "stressLevel": 43,
    "sleepHours": 7.8,
    "dietScore": "Heavy Junk",
    "caffeineIntake": "1-2 cups",
    "exercised": false,
    "notes": "Earnings season in full swing. Only trading post-earnings breakdowns with confirmation."
  },
  {
    "date": "2026-02-27",
    "moodScore": 5,
    "energyLevel": 84,
    "stressLevel": 29,
    "sleepHours": 6.8,
    "dietScore": "Clean",
    "caffeineIntake": "None",
    "exercised": true,
    "notes": "Partner distracted me during a key entry. Need to improve my trading environment."
  }
];
}
